name: Replicated Installers Support Digest

on:
  schedule:
    - cron:  '0 19 * * *'   # 7:00 PM UTC (2:00 PM Eastern DST / 3:00 PM Eastern ST) daily
  workflow_dispatch:         # manual run option

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # we need bot-state branch
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install PyGithub openai slack_sdk python-dotenv
      - name: Run digest
        env:
          GH_TOKEN: ${{ secrets.REPLICATED_SUPPORT_PAT }}   # org-scoped PAT
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SUPPORT_DIGEST_WEBHOOK }}
        run: python .github/scripts/support_digest.py
